name: easydeli
description: A new Flutter project.

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  google_fonts: ^3.0.1
  firebase_auth: ^4.0.2
  firebase_core: ^2.1.0
  cupertino_icons: ^1.0.2
  country_picker: ^2.0.16
  provider: ^6.0.4
  pinput: ^2.2.16
  shared_preferences: ^2.0.15




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg


